# Generated by Django 4.2.3 on 2023-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='defaultuserprofile.png', null=True, upload_to='profiles/'),
        ),
    ]
