# Generated by Django 4.2.3 on 2023-07-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE')], max_length=10, null=True),
        ),
    ]
