# Generated by Django 4.2.2 on 2023-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_studentprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPresident',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ADVISOR', 'Advisor'), ('STUDENT', 'Student'), ('CLUBPRESIDENT', 'Club President')], max_length=20),
        ),
    ]
