# Generated by Django 4.2.3 on 2023-07-29 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_recruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(choices=[('UB20202', 'UB20202'), ('UB60101', 'UB60101'), ('UB60909', 'UB60909')], max_length=20)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('achieved_date', models.DateField()),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
    ]
