# Generated by Django 4.2.3 on 2023-07-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_rename_room_event_rename_event_event_eventname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='assigned_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='remaining_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='total_budget',
            field=models.IntegerField(default=0),
        ),
    ]
