# Generated by Django 4.2.3 on 2023-07-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_club_assigned_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_mail', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='achivements/')),
                ('title', models.CharField(max_length=200)),
                ('achieved_date', models.DateField()),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.DeleteModel(
            name='Achivements',
        ),
    ]
