# Generated by Django 4.2.3 on 2023-07-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_short_name_alter_clubinfo_photo_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubinfo',
            name='achieved_date',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='title',
        ),
    ]
