# Generated by Django 4.2.3 on 2023-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_achievement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
