# Generated by Django 4.2.3 on 2023-08-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_remove_event_is_booked_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.CharField(choices=[('UB20202', 'UB20202'), ('UB60101', 'UB60101'), ('UB60909', 'UB60909')], default='Outdoor', max_length=20),
        ),
    ]
