# Generated by Django 4.2.3 on 2023-08-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_event_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.CharField(choices=[('UB20202', 'UB20202'), ('UB60101', 'UB60101'), ('UB60909', 'UB60909')], max_length=20),
        ),
    ]
