# Generated by Django 4.2.2 on 2023-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enrollurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
