# Generated by Django 4.2.2 on 2023-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_alter_event_enrollurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.CharField(blank=True, choices=[('UB20202', 'UB20202'), ('UB60101', 'UB60101'), ('UB60909', 'UB60909')], max_length=20),
        ),
    ]
