# Generated by Django 4.2.2 on 2023-08-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_alter_event_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='title',
            field=models.CharField(choices=[('Golden', 'Golden'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=50, null=True),
        ),
    ]
