# Generated by Django 4.2.2 on 2023-08-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0023_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.IntegerField(default=0)),
                ('remaining_budget', models.IntegerField(default=0)),
                ('assigned_budget', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='assigned_budget',
        ),
        migrations.RemoveField(
            model_name='club',
            name='remaining_budget',
        ),
        migrations.RemoveField(
            model_name='club',
            name='total_budget',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='club.budget')),
            ],
        ),
    ]
