# Generated by Django 4.2.2 on 2023-08-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0024_budget_remove_club_assigned_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
    ]
