# Generated by Django 4.2.2 on 2023-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_budget_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
