# Generated by Django 4.2.2 on 2023-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0027_club_president'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='designation',
            field=models.CharField(choices=[('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Senior Executive', 'Senior Executive'), ('Executive', 'Executive'), ('Member', 'Member')], max_length=50),
        ),
    ]
