# Generated by Django 4.2.3 on 2023-08-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0028_alter_membership_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
